{% set version = "0.1.5" %}
{% set build = 0 %}

package:
  name: pygotm
  version: {{ version }}

source:
  #git_url: https://github.com/BoldingBruggeman/pygotm.git
  url: https://github.com/BoldingBruggeman/pygotm/releases/download/v{{ version }}/code.tar.gz
  sha256: f8876848717a5bd5211e481e93437b01b20633d48dd9e286f0a38896a7e7e335

build:
  number: {{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make                                   # [not win]
    - {{ compiler('c') }}                    # [not win] NB on windows this would activate Visual Studio and make that the default C/C++ compiler
    - {{ compiler('fortran') }}              # [not win]
    - {{ stdlib("c") }}                      # [not win] on Windows this pulls in VS and causes cmake to use its cl.exe, which is incompatible with the m2w64 version of windres.exe
    - ninja                                  # [win]
    - {{ compiler('m2w64_c') }}              # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ stdlib("m2w64_c") }}                # [win]
  host:
    - python {{ python }}
    - cython
    - pip
    - setuptools
    - numpy
    - libpython                              # [win]
  run:
    - python
    #- m2w64-gcc-libgfortran                  # [win] NB m2w64-gcc-libs and m2w64-gcc-libs-core are added automatically by m2w64 compiler functions under build


test:
  imports:
    - pygotm

about:
  home: https://github.com/BoldingBruggeman/pygotm
  summary: 'Python interface to the General Ocean Turbulence Model'
  description: |
    This package provides access to the turbulence and vertical diffusion
    algorithms of the General Ocean Turbulence Model
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
