{% set version = "0.1.3" %}
{% set build = 0 %}

package:
  name: pygotm
  version: {{ version }}

source:
  #git_url: https://github.com/BoldingBruggeman/pygotm.git
  url: https://github.com/BoldingBruggeman/pygotm/releases/download/v{{ version }}/code.tar.gz
  sha256: ac5b4de3edeb48e3a008c0202af786f47e6fe22978b322028cbbcae0f9b69f60

build:
  number: {{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make                                   # [not win]
    - ninja                                  # [win]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
  host:
    - python {{ python }}
    - cython
    - pip
    - setuptools
    - numpy
    - libpython                              # [win]
  run:
    - python


test:
  imports:
    - pygotm

about:
  home: https://github.com/BoldingBruggeman/pygotm
  summary: 'Python interface to the General Ocean Turbulence Model'
  description: |
    This package provides access to the turbulence and vertical diffusion
    algorithms of the General Ocean Turbulence Model
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
